services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails-ec2_development
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 30
    ports:
      - "5432:5432"

  web:
    build: .
    # entrypoint.sh が最後に exec で rails サーバを起動する想定
    entrypoint: ["/usr/bin/entrypoint.sh"]
    command: bash -c "yarn build && yarn build:css && bundle exec rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ap-northeast-1
      S3_BUCKET_NAME: rails-ec
    volumes:
      - .:/myapp
      - node_modules:/myapp/node_modules
      - storage:/myapp/storage
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  node_modules:
  storage:
