version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: myapp_development
    networks:
      - app-network

  web:
    build: .
    image: rails_template:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
      - ./app/assets/images:/myapp/app/assets/images
      - ./config/master.key:/myapp/config/master.key:ro  # master.keyをマウント
      - ./config/credentials.yml.enc:/myapp/config/credentials.yml.enc:ro  # credentials.yml.encをマウント
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_MASTER_KEY: cdd370372d2b8c12f47f63cd73821766
      RAILS_ENV: development
    env_file:
      - .env
    networks:
      - app-network

  js:
    image: rails_template:latest
    command: yarn build --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true
    networks:
      - app-network

  css:
    image: rails_template:latest
    command: yarn build:css --watch
    volumes:
      - .:/myapp
      - bundle:/usr/local/bundle
      - node_modules:/myapp/node_modules
    tty: true
    networks:
      - app-network

volumes:
  db:
  bundle:
  node_modules:

networks:
  app-network:
    driver: bridge
