default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "postgres" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "rails-ec2_development" %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
