default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: username
  password: password
  host: db

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ubno5qcef21kaq
  password: p1a22399817ac044c7f55c80a2838b11a22d69e6c52d98936148edf513f1bb3cc
  host: db
  url: <%= ENV['DATABASE_URL'] %>

