default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: uemuraryuuta
  password: password
  host: localhost

development:
  <<: *default
  database: rails_ec2_development

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: uemuraryuuta
  password: password
  host: localhost
  database: rails_ec2_test

production:
  <<: *default
  database: rails_ec2_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
