default: &default
  adapter: postgresql
  encoding: unicode
  # DB_HOST が設定されていればその値を、なければ localhost を使う
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "postgres" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] || "rails-ec2_development" %>

test:
  <<: *default
  # テスト環境は「開発用DB名+_test」
  database: <%= ENV["POSTGRES_DB"] || "rails-ec2_development" %>_test

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
