# Amazon S3 設定
amazon: &default
  service: S3
  access_key_id: <%= Rails.application.credentials.aws[:access_key_id] %>
  secret_access_key: <%= Rails.application.credentials.aws[:secret_access_key] %>
  # region: <%= ENV['AWS_REGION'] %>
  region: 'rails-ec'
  bucket: <%= ENV['S3_BUCKET_NAME'] %>

development:
  <<: *default

production:
  <<: *default

# 必要に応じてその他のストレージサービスの設定
# Google Cloud Storage
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket-<%= Rails.env %>

# Azure Storage
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name-<%= Rails.env %>

# ローカルストレージの設定
# local:
#   service: Disk
#   root: <%= Rails.root.join("storage") %>